@JobManager.API_HostAddress = http://localhost:5073/api

### Create a new job (EF Core)
POST http://localhost:5073/api/jobs
Content-Type: application/json

{
  "title": "Dotnet Teste",
  "description": "Teste de APIs com ASP.NET Core.",
  "minSalary": 5000,
  "maxSalary": 9000,
  "company": "Acme Corp"
}

### Get all jobs (EF Core)
GET http://localhost:5073/api/jobs

### Apply to a job (EF Core)
POST http://localhost:5073/api/jobs/3/job-applications
Content-Type: application/json

{
  "candidateName": "Teste download",
  "candidateEmail": "teste.doe@example.com"
}

### Create a new job (DynamoDB)
POST http://localhost:5073/api/v2/jobs
Content-Type: application/json

{
  "id": 2,
  "title": "Frontend Developer",
  "description": "Build UI with Blazor or React.",
  "minSalary": 4000,
  "maxSalary": 8000,
  "company": "NextGen"
}

### Get all jobs (DynamoDB)
GET http://localhost:5073/api/v2/jobs

### Apply to a job (DynamoDB)
POST http://localhost:5073/api/v2/jobs/2/job-applications
Content-Type: application/json

{
  "candidateName": "Jane Smith",
  "candidateEmail": "jane.smith@example.com"
}

### Upload a CV to a job application
# Replace `<path_to_file>` with the actual path of the file on disk (if using tools like REST Client in VSCode that support it)
PUT http://localhost:5073/api/job-applications/1/upload-cv
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="cv.pdf"
Content-Type: application/pdf

< ./cv.pdf
--boundary--